<a href="https://colab.research.google.com/github/aaryanshlok0/ML-ZoomCamp/blob/main/pandas_nyc.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
df=pd.read_csv("employees_100.csv")

In [ ]:
df.head() #what does my data look like , provides fist 5 rows of data

,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date
0,184,Swati Kapoor,Data Science,Kolkata,38.0,70719,5,5,6,2021-07-02
1,154,Kavya Malhotra,engineering,Mumbai,NaN,77058,1,8,8,2024-02-05
2,171,Manish Desai,Data Science,Hyderabad,23.0,69911,0,6,18,2019-04-24
3,146,Neha Das,Engineering,Pune,28.0,69993,3,8,1,2022-12-13
4,145,Isha Nair,Data Science,NaN,32.0,88216,8,8,14,2019-11-25

In [ ]:
df.tail() #provides last 5 row

,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date
95,161,Nikhil Nair,MARKETING,Chennai,22.0,55740,0,5,22,2020-04-22
96,172,Neha Desai,HR,Chennai,22.0,52250,0,5,7,2020-11-14
97,115,Neha Reddy,Marketing,Chennai,43.0,NaN,12,4,10,2019-06-06
98,193,Priya Nayak,HR,NaN,23.0,56821,3,9,16,2019-08-07
99,152,Kavya Joshi,Marketing,Delhi,44.0,69499,10,7,4,2022-03-25

In [ ]:
df.sample(5) #to randomly slice data () would give 1, (4) would give 4 rows

,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date
93,183,Deepak Nayak,Marketing,Hyderabad,28.0,62393,2,5,13,2020-08-09
0,184,Swati Kapoor,Data Science,Kolkata,38.0,70719,5,5,6,2021-07-02
43,196,Sanjay Pillai,Marketing,Bangalore,NaN,60503,0,8,15,2022-11-08
5,140,Rahul Gupta,Sales,Hyderabad,23.0,52404,0,9,13,2018-12-27
19,132,Swati Malhotra,Engineering,Chennai,33.0,77222,5,7,15,2018-10-09

In [ ]:
df.shape #(rows,col)

(100, 10)

In [ ]:
df.dtypes #provide data type of each row , object is string

employee_id             int64
name                   object
department             object
city                   object
age                   float64
salary                 object
experience              int64
performance_score       int64
projects_completed      int64
joining_date           object
dtype: object

In [ ]:
df.info() #provides a look at data like dtype non null column name etc

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   employee_id         100 non-null    int64
 1   name                100 non-null    object
 2   department          92 non-null     object
 3   city                90 non-null     object
 4   age                 94 non-null     float64
 5   salary              92 non-null     object
 6   experience          100 non-null    int64
 7   performance_score   100 non-null    int64
 8   projects_completed  100 non-null    int64
 9   joining_date        100 non-null    object
dtypes: float64(1), int64(4), object(5)
memory usage: 7.9+ KB

In [ ]:
df.describe() #provides mean median mode std deviation etc works only on numeric col

,employee_id,age,experience,performance_score,projects_completed
count,100.000000,94.000000,100.000000,100.0000,100.000000
mean,148.740000,30.861702,4.830000,5.7500,9.970000
std,27.420637,6.483397,3.755279,1.7019,5.332301
min,101.000000,22.000000,0.000000,2.0000,0.000000
25%,125.750000,25.250000,2.000000,5.0000,6.000000
50%,149.500000,31.000000,4.500000,6.0000,9.500000
75%,171.250000,35.750000,8.000000,7.0000,13.250000
max,196.000000,45.000000,17.000000,10.0000,24.000000

In [ ]:
df.isnull() #provides null values in each col df.isnull().sum() provides sum of theirs

,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date
0,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,True,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False
4,False,False,False,True,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...
95,False,False,False,False,False,False,False,False,False,False
96,False,False,False,False,False,False,False,False,False,False
97,False,False,False,False,False,True,False,False,False,False
98,False,False,False,True,False,False,False,False,False,False
99,False,False,False,False,False,False,False,False,False,False

In [ ]:
df.isnull().sum()

employee_id            0
name                   0
department             8
city                  10
age                    6
salary                 8
experience             0
performance_score      0
projects_completed     0
joining_date           0
dtype: int64

# SELECTING AND FILTERING DATA

In [ ]:
df['salary'] #selecting one column(series)

0     70719
1     77058
2     69911
3     69993
4     88216
      ...
95    55740
96    52250
97      NaN
98    56821
99    69499
Name: salary, Length: 100, dtype: object

In [ ]:
df[['salary','name']] #if want to select multiple , then pass a list of columns, can perform all functions on these as well

   salary            name
0   70719    Swati Kapoor
1   77058  Kavya Malhotra
2   69911    Manish Desai
3   69993        Neha Das
4   88216       Isha Nair
..    ...             ...
95  55740     Nikhil Nair
96  52250      Neha Desai
97    NaN      Neha Reddy
98  56821     Priya Nayak
99  69499     Kavya Joshi

[100 rows x 2 columns]

In [ ]:
df[['salary','name']].head() #can perform functions on these as well

  salary            name
0  70719    Swati Kapoor
1  77058  Kavya Malhotra
2  69911    Manish Desai
3  69993        Neha Das
4  88216       Isha Nair

In [ ]:
#selecting rows
#using .loc and .iloc

In [ ]:
df=df.set_index("employee_id").head() #employee id becomes index

In [ ]:
df.loc[[184,145]] #.loc works on index that we have set

,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date
employee_id,,,,,,,,,
184,Swati Kapoor,Data Science,Kolkata,38.0,70719,5,5,6,2021-07-02
145,Isha Nair,Data Science,NaN,32.0,88216,8,8,14,2019-11-25

In [ ]:
#can slice out rows as well
df.loc[184:146]

,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date
employee_id,,,,,,,,,
184,Swati Kapoor,Data Science,Kolkata,38.0,70719,5,5,6,2021-07-02
154,Kavya Malhotra,engineering,Mumbai,NaN,77058,1,8,8,2024-02-05
171,Manish Desai,Data Science,Hyderabad,23.0,69911,0,6,18,2019-04-24
146,Neha Das,Engineering,Pune,28.0,69993,3,8,1,2022-12-13

In [ ]:
df.iloc[0] #works on indexing , can use with it slicing as well in similar way

name                  Swati Kapoor
department            Data Science
city                       Kolkata
age                           38.0
salary                       70719
experience                       5
performance_score                5
projects_completed               6
joining_date            2021-07-02
Name: 184, dtype: object

In [ ]:
df.loc[154:145][['city','age','salary']] #first indexed rows and then selected specific col we wanted

                  city   age salary
employee_id
154             Mumbai   NaN  77058
171          Hyderabad  23.0  69911
146               Pune  28.0  69993
145                NaN  32.0  88216

In [ ]:
#similar using iloc
df.iloc[1:5][['city','age','salary']]

                  city   age salary
employee_id
154             Mumbai   NaN  77058
171          Hyderabad  23.0  69911
146               Pune  28.0  69993
145                NaN  32.0  88216

In [ ]:
####differnce in loc and iloc
"""

df.loc[0:5] both are inclusive as its working on our values , however df.iloc[0:5] 5 is exclusive as its working on indexes

"""

In [ ]:
df['age']>40 #comparison operators on the data

0     False
1     False
2     False
3     False
4     False
      ...
95    False
96    False
97     True
98    False
99     True
Name: age, Length: 100, dtype: bool

In [ ]:
df[df['age']>40] #sending the bool values into df to get the values, can save it in a var as well

,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date
18,113,Ritu Nair,Finance,NaN,41.0,74778,10,7,5,2018-02-13
55,179,Arjun Das,Finance,NaN,43.0,NaN,10,7,11,2024-08-25
61,164,Sneha Gupta,NaN,Delhi,42.0,63209,11,3,8,2021-08-07
62,155,Sanjay Das,NaN,Bangalore,45.0,74505,17,6,10,2022-06-22
76,176,Shreya Menon,Finance,NaN,41.0,80597,9,2,18,2024-11-09
80,164,Sneha Gupta,NaN,Delhi,42.0,63209,11,4,7,2021-08-07
88,124,Deepak Verma,Data Science,Hyderabad,41.0,86380,9,7,8,2024-06-05
97,115,Neha Reddy,Marketing,Chennai,43.0,NaN,12,4,10,2019-06-06
99,152,Kavya Joshi,Marketing,Delhi,44.0,69499,10,7,4,2022-03-25

In [ ]:
#pandas uses and or and not like bitwise in cpp(& , | , ~)

In [ ]:
#give me people working in finance and their ages are above 30

In [ ]:
df[(df['department']=='Finance') & (df['age']>30) & ((df['performance_score']>6) | (df['experience']>10))] #important

,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date
18,113,Ritu Nair,Finance,NaN,41.0,74778,10,7,5,2018-02-13
55,179,Arjun Das,Finance,NaN,43.0,NaN,10,7,11,2024-08-25
82,138,Rahul Gupta,Finance,Hyderabad,35.0,"75,614",11,7,14,2020-10-18

In [ ]:
#useful filtering method

In [ ]:
df[df['department'].isin(['Engineering','Data Science'])] #using isin to find

,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date
0,184,Swati Kapoor,Data Science,Kolkata,38.0,70719,5,5,6,2021-07-02
2,171,Manish Desai,Data Science,Hyderabad,23.0,69911,0,6,18,2019-04-24
3,146,Neha Das,Engineering,Pune,28.0,69993,3,8,1,2022-12-13
4,145,Isha Nair,Data Science,NaN,32.0,88216,8,8,14,2019-11-25
8,111,Kavya Singh,Engineering,Delhi,23.0,NaN,1,5,10,2021-09-14
15,105,Vivek Pillai,Engineering,Pune,39.0,NaN,9,4,5,2024-06-05
19,132,Swati Malhotra,Engineering,Chennai,33.0,77222,5,7,15,2018-10-09
20,156,Aditya Kapoor,Data Science,Kolkata,26.0,69765,0,2,4,2020-04-12
22,127,Suresh Verma,Data Science,Bangalore,27.0,"72,862",2,6,10,2023-02-21
24,170,Rahul Nair,Data Science,Kolkata,30.0,76425,5,2,4,2021-06-25
25,116,Rohan Verma,Engineering,Chennai,23.0,62693,0,4,8,2018-08-17
31,148,Kavya Nair,Engineering,Chennai,NaN,"76,320",3,7,11,2024-03-07
34,194,Pooja Menon,Engineering,Chennai,NaN,76281,7,4,9,2022-07-28
42,108,Ananya Rao,Engineering,Pune,38.0,78545,6,5,10,2022-02-16
54,109,Rohan Kulkarni,Data Science,Delhi,28.0,76267,5,6,3,2023-01-24
59,190,Swati Bose,Data Science,Mumbai,22.0,78465,0,8,18,2022-11-22
60,157,Ananya Rao,Engineering,Mumbai,25.0,NaN,2,5,8,2022-04-07
63,144,Arjun Nayak,Engineering,Kolkata,38.0,75226,7,6,17,2019-12-27
65,168,Sanjay Kulkarni,Engineering,Delhi,34.0,80358,7,5,14,2020-04-01
66,147,Tanvi Verma,Engineering,Bangalore,35.0,77217,8,3,0,2022-04-22
84,102,Rahul Menon,Engineering,Hyderabad,38.0,84870,11,6,15,2021-06-07
88,124,Deepak Verma,Data Science,Hyderabad,41.0,86380,9,7,8,2024-06-05
92,187,Aditya Bose,Engineering,Bangalore,36.0,81112,7,4,9,2022-03-26
94,121,Ashok Shah,Data Science,Pune,31.0,75498,4,7,7,2024-12-05

In [ ]:
df[df['experience'].between(2,5)] #inclusive range both

,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date
0,184,Swati Kapoor,Data Science,Kolkata,38.0,70719,5,5,6,2021-07-02
3,146,Neha Das,Engineering,Pune,28.0,69993,3,8,1,2022-12-13
6,123,Sneha Iyer,HR,Hyderabad,33.0,59895,4,4,18,2024-02-21
9,101,Ananya Malhotra,engineering,NaN,24.0,68591,2,8,0,2023-10-21
13,134,Vivek Kulkarni,Finance,Kolkata,24.0,59422,3,6,12,2021-11-24
14,191,Neha Malhotra,Marketing,Mumbai,29.0,64944,2,10,18,2023-10-05
16,177,Vivek Malhotra,Finance,Bangalore,NaN,NaN,3,4,12,2021-09-12
17,178,Vikram Kapoor,Sales,Chennai,29.0,57858,3,7,1,2020-06-26
19,132,Swati Malhotra,Engineering,Chennai,33.0,77222,5,7,15,2018-10-09
22,127,Suresh Verma,Data Science,Bangalore,27.0,"72,862",2,6,10,2023-02-21
24,170,Rahul Nair,Data Science,Kolkata,30.0,76425,5,2,4,2021-06-25
26,141,Manish Kulkarni,HR,Chennai,27.0,"45,835",3,8,13,2022-07-21
27,162,Suresh Chatterjee,HR,Hyderabad,32.0,59273,5,6,11,2020-09-05
28,110,Arjun Verma,Marketing,Pune,29.0,62227,4,7,8,2022-04-05
29,173,Riya Shah,Marketing,Bangalore,27.0,"62,165",5,5,6,2021-10-07
30,112,Aditya Reddy,Finance,NaN,31.0,58811,2,3,3,2020-05-26
31,148,Kavya Nair,Engineering,Chennai,NaN,"76,320",3,7,11,2024-03-07
35,106,Vivek Singh,HR,Delhi,27.0,56886,3,6,11,2020-08-04
36,167,Meera Malhotra,HR,Hyderabad,31.0,48822,4,5,4,2022-06-24
37,166,Meera Nayak,HR,Hyderabad,33.0,56940,4,7,13,2023-04-14
38,136,Sanjay Mehta,Sales,Hyderabad,30.0,52573,5,7,8,2021-02-12
41,135,Meera Desai,Marketing,Kolkata,28.0,59186,4,6,8,2023-07-10
53,139,Rahul Malhotra,Marketing,Hyderabad,23.0,60203,2,6,15,2022-09-17
54,109,Rohan Kulkarni,Data Science,Delhi,28.0,76267,5,6,3,2023-01-24
60,157,Ananya Rao,Engineering,Mumbai,25.0,NaN,2,5,8,2022-04-07
64,151,Sneha Verma,Finance,Delhi,NaN,66422,5,6,5,2023-09-02
67,169,Swati Chatterjee,HR,Pune,33.0,49801,3,6,11,2021-08-20
68,162,Suresh Chatterjee,HR,Hyderabad,32.0,59273,5,7,11,2020-09-05
69,134,Vivek Kulkarni,Finance,Kolkata,24.0,59422,3,6,13,2021-11-24
70,180,Ashok Kulkarni,Finance,Kolkata,31.0,58777,3,5,9,2024-07-10
72,159,Rohan Menon,HR,Pune,26.0,56141,3,4,13,2023-01-03
77,133,Riya Verma,HR,Kolkata,26.0,59693,3,6,20,2024-05-08
79,160,Shreya Singh,Finance,Pune,38.0,62020,5,5,0,2019-05-11
86,122,Ashok Shah,HR,Hyderabad,31.0,55756,5,8,11,2024-05-11
91,175,Aman Nayak,NaN,NaN,27.0,69076,5,5,10,2019-09-15
93,183,Deepak Nayak,Marketing,Hyderabad,28.0,62393,2,5,13,2020-08-09
94,121,Ashok Shah,Data Science,Pune,31.0,75498,4,7,7,2024-12-05
98,193,Priya Nayak,HR,NaN,23.0,56821,3,9,16,2019-08-07

# CLEANING DATA

In [ ]:
df.isnull().sum()

employee_id            0
name                   0
department             8
city                  10
age                    6
salary                 8
experience             0
performance_score      0
projects_completed     0
joining_date           0
dtype: int64

In [ ]:
df2=df.dropna() #dropping all the rows having null values , now only 71 rows are left rest 29 had null values in a column or another so they got removed

In [ ]:
df2.isnull().sum() #the problem is that 29 rows got deleted out of 100 so not the  rigth way

employee_id           0
name                  0
department            0
city                  0
age                   0
salary                0
experience            0
performance_score     0
projects_completed    0
joining_date          0
dtype: int64

In [ ]:
df.dropna(subset=['city']) #10 rows got dropped with null values in city

,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date
0,184,Swati Kapoor,Data Science,Kolkata,38.0,70719,5,5,6,2021-07-02
1,154,Kavya Malhotra,engineering,Mumbai,NaN,77058,1,8,8,2024-02-05
2,171,Manish Desai,Data Science,Hyderabad,23.0,69911,0,6,18,2019-04-24
3,146,Neha Das,Engineering,Pune,28.0,69993,3,8,1,2022-12-13
5,140,Rahul Gupta,Sales,Hyderabad,23.0,52404,0,9,13,2018-12-27
...,...,...,...,...,...,...,...,...,...,...
94,121,Ashok Shah,Data Science,Pune,31.0,75498,4,7,7,2024-12-05
95,161,Nikhil Nair,MARKETING,Chennai,22.0,55740,0,5,22,2020-04-22
96,172,Neha Desai,HR,Chennai,22.0,52250,0,5,7,2020-11-14
97,115,Neha Reddy,Marketing,Chennai,43.0,NaN,12,4,10,2019-06-06
99,152,Kavya Joshi,Marketing,Delhi,44.0,69499,10,7,4,2022-03-25

In [ ]:
#filling those values instead of dropping entire row which can cause issues and deletion of imp data

In [ ]:
df['age']=df['age'].fillna(df['age'].median()) #df['age'] tells python to get the age series and then the rest makes calc median of non missing values and fill it

In [ ]:
df.isnull().sum() #inplace=true makes it into real data now null age = 0

employee_id            0
name                   0
department             8
city                  10
age                    0
salary                 8
experience             0
performance_score      0
projects_completed     0
joining_date           0
dtype: int64

In [ ]:
df['salary']=df['salary'].str.replace(",","",regex=False)
df['salary']=pd.to_numeric(df['salary'],errors='coerce')
df['salary']=df['salary'].fillna(df['salary'].median())

In [ ]:
df['salary'].dtype #can also use df.dtypes

dtype('float64')

In [ ]:
df.isnull().sum() #0 null values in salary and age column

employee_id             0
name                    0
department              8
city                   10
age                     0
salary                100
experience              0
performance_score       0
projects_completed      0
joining_date            0
dtype: int64

In [ ]:
#now to fill dept its not a numeric value so we would see first what kinda values are in there

In [ ]:
df['department'].value_counts()
#its a categorical col not a continuous(values ) , we fill categorical col with mode

department
HR              17
Marketing       17
Finance         16
Engineering     14
Data Science    10
Sales            8
engineering      3
 HR              2
 Marketing       1
 Finance         1
FINANCE          1
SALES            1
MARKETING        1
Name: count, dtype: int64

In [ ]:
df['department']=df['department'].fillna(df['department'].mode()[0]) #this [0] is as there are both hr and marketing with same count so we gotta select one out of these to fill

In [ ]:
df['city']=df['city'].fillna(df['city'].mode()[0])

In [ ]:
df.isnull().sum()

employee_id           0
name                  0
department            0
city                  0
age                   0
salary                0
experience            0
performance_score     0
projects_completed    0
joining_date          0
dtype: int64

In [ ]:
df.duplicated().sum() #row duplicate chk

np.int64(0)

In [ ]:
#col duplicate chk
df.duplicated(subset=['employee_id']).sum()

np.int64(4)

In [ ]:
df.drop_duplicates(subset=['employee_id']) #the 4 duplicates got removed

,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date
0,184,Swati Kapoor,Data Science,Kolkata,38.0,70719.0,5,5,6,2021-07-02
1,154,Kavya Malhotra,engineering,Mumbai,31.0,77058.0,1,8,8,2024-02-05
2,171,Manish Desai,Data Science,Hyderabad,23.0,69911.0,0,6,18,2019-04-24
3,146,Neha Das,Engineering,Pune,28.0,69993.0,3,8,1,2022-12-13
4,145,Isha Nair,Data Science,Hyderabad,32.0,88216.0,8,8,14,2019-11-25
...,...,...,...,...,...,...,...,...,...,...
95,161,Nikhil Nair,MARKETING,Chennai,22.0,55740.0,0,5,22,2020-04-22
96,172,Neha Desai,HR,Chennai,22.0,52250.0,0,5,7,2020-11-14
97,115,Neha Reddy,Marketing,Chennai,43.0,62969.5,12,4,10,2019-06-06
98,193,Priya Nayak,HR,Hyderabad,23.0,56821.0,3,9,16,2019-08-07
99,152,Kavya Joshi,Marketing,Delhi,44.0,69499.0,10,7,4,2022-03-25

In [ ]:
df['joining_date']

0     2021-07-02
1     2024-02-05
2     2019-04-24
3     2022-12-13
4     2019-11-25
         ...
95    2020-04-22
96    2020-11-14
97    2019-06-06
98    2019-08-07
99    2022-03-25
Name: joining_date, Length: 100, dtype: object

In [ ]:
#coverting text to real dates

In [ ]:
df['joining_date']=pd.to_datetime(df['joining_date'])

In [ ]:
df['joining_date'].dtype #ns stands for nanosecond precision

dtype('<M8[ns]')

In [ ]:
#renaming columns

In [ ]:
#clean every column name in one line

# Modifying data and creating new column

In [ ]:
df['annual_salary']=df['salary']*12 #a new column named annual_salary modified with the hlep of an older one

In [ ]:
#to modify current col
#df['salary']=df['salary']*12

In [ ]:
df['department']

0     Data Science
1      engineering
2     Data Science
3      Engineering
4     Data Science
          ...
95       MARKETING
96              HR
97       Marketing
98              HR
99       Marketing
Name: department, Length: 100, dtype: object

In [ ]:
#apply function

In [ ]:
df.head()

,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date
0,184,Swati Kapoor,Data Science,Kolkata,38.0,70719.0,5,5,6,2021-07-02
1,154,Kavya Malhotra,engineering,Mumbai,31.0,77058.0,1,8,8,2024-02-05
2,171,Manish Desai,Data Science,Hyderabad,23.0,69911.0,0,6,18,2019-04-24
3,146,Neha Das,Engineering,Pune,28.0,69993.0,3,8,1,2022-12-13
4,145,Isha Nair,Data Science,Hyderabad,32.0,88216.0,8,8,14,2019-11-25

In [ ]:
def categorize(num):
  if num>5:
    return "Experienced Candidate"
    #always use a return while using apply function in pandas
  elif num<=5:
    return "Leaner"

In [ ]:
df['experience_status']=df['experience'].apply(categorize)

In [ ]:
df.head()

,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date,experience_status
0,184,Swati Kapoor,Data Science,Kolkata,38.0,70719.0,5,5,6,2021-07-02,Leaner
1,154,Kavya Malhotra,engineering,Mumbai,31.0,77058.0,1,8,8,2024-02-05,Leaner
2,171,Manish Desai,Data Science,Hyderabad,23.0,69911.0,0,6,18,2019-04-24,Leaner
3,146,Neha Das,Engineering,Pune,28.0,69993.0,3,8,1,2022-12-13,Leaner
4,145,Isha Nair,Data Science,Hyderabad,32.0,88216.0,8,8,14,2019-11-25,Experienced Candidate

# Sorting and Ranking

In [ ]:
#after analyzing the data, u usually want the extremes highest lowest best or worst

In [ ]:
df.sort_values(by="employee_id",ascending=False) #to sort in descending order

,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date,experience_status
43,196,Sanjay Pillai,Marketing,Bangalore,31.0,60503.0,0,8,15,2022-11-08,Leaner
78,195,Pooja Nair,Finance,Hyderabad,33.0,69396.0,6,6,4,2023-01-13,Experienced Candidate
34,194,Pooja Menon,Engineering,Chennai,31.0,76281.0,7,4,9,2022-07-28,Experienced Candidate
98,193,Priya Nayak,HR,Hyderabad,23.0,56821.0,3,9,16,2019-08-07,Leaner
90,192,Divya Verma,HR,Delhi,40.0,66363.0,12,7,13,2022-09-10,Experienced Candidate
...,...,...,...,...,...,...,...,...,...,...,...
15,105,Vivek Pillai,Engineering,Pune,39.0,62969.5,9,4,5,2024-06-05,Experienced Candidate
51,104,Ritu Iyer,Marketing,Bangalore,34.0,63574.0,8,7,20,2021-05-10,Experienced Candidate
87,103,Ananya Nayak,Sales,Delhi,38.0,68490.0,9,6,6,2021-11-19,Experienced Candidate
84,102,Rahul Menon,Engineering,Hyderabad,38.0,84870.0,11,6,15,2021-06-07,Experienced Candidate
9,101,Ananya Malhotra,engineering,Hyderabad,24.0,68591.0,2,8,0,2023-10-21,Leaner

In [ ]:
df.sort_values(by=['department','salary'],ascending=[True,False])

,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date,experience_status
16,177,Vivek Malhotra,Finance,Bangalore,31.0,62969.5,3,4,12,2021-09-12,Leaner
27,162,Suresh Chatterjee,HR,Hyderabad,32.0,59273.0,5,6,11,2020-09-05,Leaner
68,162,Suresh Chatterjee,HR,Hyderabad,32.0,59273.0,5,7,11,2020-09-05,Leaner
11,131,Priya Malhotra,Marketing,Hyderabad,25.0,55295.0,1,7,12,2022-02-13,Leaner
4,145,Isha Nair,Data Science,Hyderabad,32.0,88216.0,8,8,14,2019-11-25,Experienced Candidate
...,...,...,...,...,...,...,...,...,...,...,...
38,136,Sanjay Mehta,Sales,Hyderabad,30.0,52573.0,5,7,8,2021-02-12,Leaner
5,140,Rahul Gupta,Sales,Hyderabad,23.0,52404.0,0,9,13,2018-12-27,Leaner
39,117,Pooja Malhotra,engineering,Kolkata,24.0,84255.0,1,8,19,2021-12-05,Leaner
1,154,Kavya Malhotra,engineering,Mumbai,31.0,77058.0,1,8,8,2024-02-05,Leaner
9,101,Ananya Malhotra,engineering,Hyderabad,24.0,68591.0,2,8,0,2023-10-21,Leaner

In [ ]:
df['department'].unique()

array(['Engineering', 'Sales', 'Marketing', 'Hr', 'Data Science',
       'Finance'], dtype=object)

In [ ]:
df['department']=df['department'].str.strip().str.title()

In [ ]:
df["salary_rank"]=df["salary"].rank()
df.sort_values(by='salary_rank')

,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date,experience_status,salary_rank,salary_rank
26,141,Manish Kulkarni,Hr,Chennai,27.0,45835.0,3,8,13,2022-07-21,Leaner,1.0,1.0
36,167,Meera Malhotra,Hr,Hyderabad,31.0,48822.0,4,5,4,2022-06-24,Leaner,2.0,2.0
33,129,Ashok Gupta,Marketing,Hyderabad,22.0,49693.0,0,4,7,2018-08-27,Leaner,3.0,3.0
67,169,Swati Chatterjee,Hr,Pune,33.0,49801.0,3,6,11,2021-08-20,Leaner,4.0,4.0
7,181,Karan Rao,Marketing,Hyderabad,22.0,50733.0,1,6,6,2020-04-05,Leaner,5.0,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
84,102,Rahul Menon,Engineering,Hyderabad,38.0,84870.0,11,6,15,2021-06-07,Experienced Candidate,96.0,96.0
88,124,Deepak Verma,Data Science,Hyderabad,41.0,86380.0,9,7,8,2024-06-05,Experienced Candidate,97.0,97.0
4,145,Isha Nair,Data Science,Hyderabad,32.0,88216.0,8,8,14,2019-11-25,Experienced Candidate,98.0,98.0
75,158,Tanvi Malhotra,Hr,Mumbai,32.0,88366.0,11,6,17,2021-02-26,Experienced Candidate,99.5,99.5
74,158,Tanvi Malhotra,Hr,Mumbai,32.0,88366.0,11,5,19,2021-02-26,Experienced Candidate,99.5,99.5

In [ ]:
df

,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date,experience_status,salary_rank
9,101,Ananya Malhotra,Engineering,Hyderabad,24.0,68591.0,2,8,0,2023-10-21,Leaner,67.0
84,102,Rahul Menon,Engineering,Hyderabad,38.0,84870.0,11,6,15,2021-06-07,Experienced Candidate,96.0
87,103,Ananya Nayak,Sales,Delhi,38.0,68490.0,9,6,6,2021-11-19,Experienced Candidate,66.0
51,104,Ritu Iyer,Marketing,Bangalore,34.0,63574.0,8,7,20,2021-05-10,Experienced Candidate,57.0
15,105,Vivek Pillai,Engineering,Pune,39.0,62969.5,9,4,5,2024-06-05,Experienced Candidate,50.5
...,...,...,...,...,...,...,...,...,...,...,...,...
90,192,Divya Verma,Hr,Delhi,40.0,66363.0,12,7,13,2022-09-10,Experienced Candidate,62.0
98,193,Priya Nayak,Hr,Hyderabad,23.0,56821.0,3,9,16,2019-08-07,Leaner,21.0
34,194,Pooja Menon,Engineering,Chennai,31.0,76281.0,7,4,9,2022-07-28,Experienced Candidate,84.0
78,195,Pooja Nair,Finance,Hyderabad,33.0,69396.0,6,6,4,2023-01-13,Experienced Candidate,69.0
43,196,Sanjay Pillai,Marketing,Bangalore,31.0,60503.0,0,8,15,2022-11-08,Leaner,39.0